name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Start server and run Lighthouse
        run: |
          npm install -g @lhci/cli@0.13.x wait-on
          npm run start & 
          wait-on http://localhost:3000
          lhci autorun
          kill $(lsof -t -i:3000) || true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci/ 